id: clustering_benchmark
description: Clustering benchmark on Gagolewski's, true number of clusters only.
version: 1.0
benchmarker: "Omnibenchmark Team at Mark D. Robinson lab"
storage: https://play.min.io
benchmark_yaml_spec: 0.01
storage_api: S3
storage_bucket_name: clustering_benchmark
software_backend: conda
software_environments:
  clustbench:
    description: "clustbench on py3.12.6"
    conda: envs/clustbench.yml
stages:
  - id: data
    modules:
      - id: clustbench
        name: "clustbench datasets"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_data
          commit: 366c5a2
        parameters:
          - values: ["--dataset_generator", "mnist", "--dataset_name", "fashion"]
          - values: ["--dataset_generator", "other", "--dataset_name", "iris"]
          - values: ["--dataset_generator", "mnist", "--dataset_name", "digits"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "circles"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "cross"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "graph"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "isolation"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "labirynth"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "mk1"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "mk2"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "mk3"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "mk4"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "olympic"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "smile"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "stripes"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "trajectories"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "trapped_lovers"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "twosplashes"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "windows"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "x1"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "x2"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "x3"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "z1"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "z2"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "z3"]
    outputs:
      - id: data.matrix
        path: "{input}/{stage}/{module}/{params}/{dataset}.data.gz"
      - id: data.true_labels
        path: "{input}/{stage}/{module}/{params}/{dataset}.labels0.gz"
  - id: clustering
    modules:
      - id: fastcluster
        name: "fastcluster algorithm"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_fastcluster
          # url: /home/imallona/src/clustbench_fastcluster/
          commit: "c64aee7"
        parameters:
          - values: ["--linkage", "complete"]
          - values: ["--linkage", "ward"]
          - values: ["--linkage", "average"]
          - values: ["--linkage", "weighted"]
          - values: ["--linkage", "median"]
          - values: ["--linkage", "centroid"]
    inputs:
      - entries:
          - data.matrix
          - data.true_labels
    outputs:
      - id: clustering.predicted
        path: "{input}/{stage}/{module}/{params}/{dataset}.labels.gz"
  - id: metrics
    modules:
      - id: partition_metrics
        name: "clustbench partition metrics"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_metrics
          commit: c48c813
        parameters:
          - values: ["--metric", "normalized_clustering_accuracy"]
          - values: ["--metric", "adjusted_fm_score"]
    inputs:
      - entries:
          - clustering.predicted
          - data.true_labels
    outputs:
      - id: metrics.scores
        path: "{input}/{stage}/{module}/{params}/{dataset}.scores.gz"