id: clustering_benchmark
description: Clustering benchmark on Iris and Penguins Dataset.
version: 1.0
benchmarker: "OmniBenchmark Team at Robinsons Lab"
storage: https://play.min.io
benchmark_yaml_spec: 0.01
storage_api: S3
storage_bucket_name: clustering_benchmark
software_backend: conda
software_environments:
  clustbench:
    description: "clustbench on py3.12.6"
    conda: envs/clustbench.yml
stages:
  - id: data
    modules:
      - id: clustbench
        name: "clustbench datasets"
        software_environment: "clustbench"
        repository:
          url: https://github.com/imallona/clustbench_data
          commit: 366c5a2
        parameters:
          - values: ["--dataset_generator", "mnist", "--dataset_name", "fashion"]
          - values: ["--dataset_generator", "other", "--dataset_name", "iris"]
          - values: ["--dataset_generator", "mnist", "--dataset_name", "digits"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "circles"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "cross"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "graph"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "isolation"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "labirynth"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "mk1"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "mk2"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "mk3"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "mk4"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "olympic"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "smile"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "stripes"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "trajectories"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "trapped_lovers"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "twosplashes"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "windows"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "x1"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "x2"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "x3"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "z1"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "z2"]
          - values: ["--dataset_generator", "wut", "--dataset_name", "z3"]
    outputs:
      - id: data.features
        path: "{input}/{stage}/{module}/{params}/{dataset}.data.gz"
      - id: data.labels
        path: "{input}/{stage}/{module}/{params}/{dataset}.labels0.gz"

  ## - id: distances
  ##   modules:
  ##     - id: D1
  ##       software_environment: "clustbench"
  ##       parameters:
  ##         - values: ["--measure", "cosine"]
  ##         - values: ["--measure", "euclidean"]
  ##         - values: ["--measure", "manhattan"]
  ##         - values: ["--measure", "chebyshev"]
  ##       repository:
  ##         url: https://github.com/omnibenchmark-example/distance.git
  ##         commit: dd99d4f
  ##   inputs:
  ##     - entries:
  ##         - data.features
  ##   outputs:
  ##     - id: distances
  ##       path: "{input}/{stage}/{module}/{params}/{dataset}.distances.csv"

  ## - id: methods
  ##   modules:
  ##     - id: kmeans
  ##       software_environment: "clustbench"
  ##       repository:
  ##         url: https://github.com/omnibenchmark-example/kmeans.git
  ##         commit: 049c8b1
  ##   inputs:
  ##     - entries:
  ##         - distances
  ##   outputs:
  ##     - id: methods.clusters
  ##       path: "{input}/{stage}/{module}/{params}/{dataset}.clusters.csv"